apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nacos-k8s-sync-{{ .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nacos-k8s-sync-{{ .Values.global.namespace }}
subjects:
  - kind: ServiceAccount
    name: nacos-k8s-sync-sa
    namespace: {{ .Values.global.namespace }}
